csvFilePath: C:\Users\sichez\Downloads\gsqlparser_dotnet_trial_3.2.2.5\demos\visitors\0-100\0-100.csv
exeOutputFilePath: C:\Users\sichez\Downloads\gsqlparser_dotnet_trial_3.2.2.5\demos\visitors\0-100\output.txt
parseOutputFilePath: C:\Users\sichez\Downloads\gsqlparser_dotnet_trial_3.2.2.5\demos\visitors\0-100\parsingOutput.xml
filesDirectory: C:\Users\sichez\Downloads\gsqlparser_dotnet_trial_3.2.2.5\demos\visitors\0-100\
exeCommand: C:\Users\sichez\Downloads\gsqlparser_dotnet_trial_3.2.2.5\demos\visitors\bin\Release\toXML.exe
exeCommandConsumingString: /t mssql /s {}
tagsToDiscard:
            - 'query_expression'
            - 'query_specification'
            - 'first_expr'
            - 'second_expr'
            - 'third_expr'
            - 'expression'
includeNoWhere: False
tableAttributeFilter:
            - ['PhotoTag', 'objID']
compress: False
skipExe: True